"""Authorship — push 前 AI 痕迹清洗

只在 push 时转换，workspace 一切不变。
- 标准模式: commit message 清洗 + AI 配置文件排除
- 激进模式: 额外去除代码中的 AI 生成注释
"""

from __future__ import annotations

import re

# Patterns for stripping AI co-authorship from commit messages
_COAUTHOR_PATTERNS = [
    re.compile(r'^Co-authored-by:.*\b(?:Claude|ChatGPT|Copilot|Cursor|GPT|Gemini|Bard)\b.*$', re.I | re.M),
    re.compile(r'\b(?:Generated|Created|Written)\s+(?:with|by)\s+(?:Claude|ChatGPT|Copilot|Cursor|GPT|Gemini|Bard)\b[^\n]*', re.I),
    re.compile(r'\bvia\s+(?:Claude|ChatGPT|Copilot|Cursor|GPT|Gemini|Bard)\b[^\n]*', re.I),
    re.compile(r'^Signed-off-by:.*\b(?:Claude|ChatGPT|Copilot|Cursor)\b.*$', re.I | re.M),
]

# Patterns for stripping AI-generated comments from code (aggressive mode)
_COMMENT_AI_PATTERNS = [
    re.compile(r'^\s*#\s*(?:Generated|Created|Written)\s+(?:with|by)\s+(?:Claude|ChatGPT|Copilot|Cursor|GPT|Gemini|Bard)\b.*$', re.I | re.M),
    re.compile(r'^\s*//\s*(?:Generated|Created|Written)\s+(?:with|by)\s+(?:Claude|ChatGPT|Copilot|Cursor|GPT|Gemini|Bard)\b.*$', re.I | re.M),
    re.compile(r'^\s*/\*\s*(?:Generated|Created|Written)\s+(?:with|by)\s+(?:Claude|ChatGPT|Copilot|Cursor|GPT|Gemini|Bard)\b.*\*/', re.I),
    re.compile(r'^\s*#\s*(?:via|AI-generated|auto-generated by)\s+(?:Claude|ChatGPT|Copilot|Cursor|GPT|Gemini|Bard)\b.*$', re.I | re.M),
    re.compile(r'^\s*//\s*(?:via|AI-generated|auto-generated by)\s+(?:Claude|ChatGPT|Copilot|Cursor|GPT|Gemini|Bard)\b.*$', re.I | re.M),
]

# AI tool config files to exclude from push
_DEFAULT_AI_CONFIG_FILES = [
    "CLAUDE.md",
    ".claude/",
    ".codex/",
    ".codebuddy/",
    ".cursor/",
    ".github/copilot-instructions.md",
    ".windsurf/",
]

# AI-tool gitignore-like patterns to add to push exclusion
_DEFAULT_AI_PATTERNS = [
    "CLAUDE.md",
    ".claude/",
    ".codex/",
    ".codebuddy/",
    ".cursor/",
    ".windsurf/",
    ".github/copilot-instructions.md",
]


def strip_commit_message(msg: str) -> str:
    """清除 commit message 中的 AI 合作署名和生成声明。"""
    result = msg
    for pattern in _COAUTHOR_PATTERNS:
        result = pattern.sub("", result)
    # 清理空行
    result = re.sub(r'\n{3,}', '\n\n', result)
    return result.strip()


def strip_code_comments(content: str) -> str:
    """清除代码中的 AI 生成注释行（激进模式）。"""
    lines = content.split('\n')
    kept = []
    for line in lines:
        stripped = line.rstrip()
        is_ai_comment = False
        for pattern in _COMMENT_AI_PATTERNS:
            if pattern.match(stripped):
                is_ai_comment = True
                break
        if not is_ai_comment:
            kept.append(line)
    return '\n'.join(kept)


def get_ai_exclude_patterns(project=None) -> list[str]:
    """获取需要从 push 中排除的 AI 配置文件列表。

    优先级: 项目配置 > 默认列表
    """
    if project and hasattr(project, 'authorship'):
        cfg = project.authorship or {}
        return cfg.get("exclude_tool_configs", list(_DEFAULT_AI_CONFIG_FILES))
    return list(_DEFAULT_AI_CONFIG_FILES)


def is_ai_config_file(rel_path: str, exclude_patterns: list[str] | None = None) -> bool:
    """检查文件是否属于 AI 工具配置文件。"""
    patterns = exclude_patterns or _DEFAULT_AI_CONFIG_FILES
    normalized = rel_path.replace("\\", "/")
    for pattern in patterns:
        p = pattern.rstrip("/")
        if normalized == p or normalized.startswith(p + "/"):
            return True
    return False


def apply_authorship_filter(
    session,  # SyncSession
    aggressive: bool = False,
) -> dict:
    """对当前 session 的 formal commits 应用著作权过滤。

    在 step_push 之前调用，修改的是 push 出去的版本。
    返回过滤统计。
    """
    cfg = getattr(session.project, 'authorship', None) or {}
    mode = cfg.get("mode", "mixed")
    if mode == "mixed":
        return {"filtered": False, "reason": "authorship.mode=mixed"}

    strip_commit = cfg.get("strip_commit_coauthors", True)
    strip_comments = aggressive or cfg.get("strip_code_comments", False)
    exclude = cfg.get("exclude_tool_configs", list(_DEFAULT_AI_CONFIG_FILES))

    stats = {"filtered": True, "commits_cleaned": 0, "files_excluded": 0}

    # 清洗 formal commit 的 message
    if strip_commit:
        for fc in session.formal_commits:
            if fc.synced and not fc.pushed:
                original = fc.message
                cleaned = strip_commit_message(original)
                if cleaned != original:
                    fc.message = cleaned
                    stats["commits_cleaned"] += 1

    # 记录 AI 配置文件的排除（实际排除由 sync 层的 exclude 处理）
    stats["exclude_patterns"] = exclude

    return stats


def strip_authorship_from_message(message: str) -> str:
    """清洗单条 commit message（CLI/MCP 可直接调用）。"""
    return strip_commit_message(message)


def strip_authorship_from_code(content: str, aggressive: bool = False) -> str:
    """清洗代码内容（CLI/MCP 可直接调用）。"""
    if aggressive:
        return strip_code_comments(content)
    return content


# ── Privacy Scan ─────────────────────────────────────────────

# Level 2: 内容模式匹配默认正则
_DEFAULT_PRIVACY_PATTERNS = {
    "email": re.compile(r'[\w.\-+]+@[\w.\-]+\.\w+'),
    "ip": re.compile(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'),
    "apikey": re.compile(r'(?:sk-[A-Za-z0-9]{20,})|(?:ghp_[A-Za-z0-9]{30,})|(?:xox[baprs]-[A-Za-z0-9-]+)'),
    "private_key": re.compile(r'-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----'),
    "internal_path": re.compile(r'(?:\\\\[\w.-]+\\[\w.-]+)|(?:\b/home/\w+)|(?:\b/Users/\w+)'),
}

# Level 3: 结构分析阈值
_STRUCTURAL_THRESHOLDS = {
    "table_columns": 5,      # 超过此列数的对齐表格
    "numeric_density": 0.3,  # 数字字符占比超过此值
}


def scan_privacy(
    file_path: str,
    content: str,
    level: int = 2,
    patterns: list[str] | None = None,
    deep_scan: bool = False,
) -> list[dict]:
    """对单个文件内容执行分级隐私扫描。返回告警列表。

    Level 1: 文件名匹配（由 force_exclude 处理，此处不重复）
    Level 2: 内容正则模式匹配
    Level 3: 结构分析（deep_scan=True 时）
    """
    alerts = []

    if level >= 2:
        active = patterns or list(_DEFAULT_PRIVACY_PATTERNS.keys())
        for name in active:
            pat = _DEFAULT_PRIVACY_PATTERNS.get(name)
            if pat is None:
                continue
            matches = pat.findall(content)
            if matches:
                # 取不重复的前 5 个匹配
                unique = list(dict.fromkeys(matches))[:5]
                alerts.append({
                    "level": "error",
                    "rule": f"privacy_{name}",
                    "message": f"Privacy violation: {len(matches)} {name} pattern(s) found in {file_path}",
                    "matches": unique,
                })

    if level >= 3 and deep_scan:
        # 表格检测：含 | 分隔符且对齐
        lines = content.split("\n")
        table_lines = [l for l in lines if l.strip().startswith("|") and l.count("|") >= _STRUCTURAL_THRESHOLDS["table_columns"] + 1]
        if len(table_lines) >= 2:
            alerts.append({
                "level": "warning",
                "rule": "privacy_tabular_data",
                "message": f"Possible tabular data in {file_path}: {len(table_lines)} table rows detected",
            })

        # 数值密度
        alpha_chars = sum(1 for c in content if c.isalpha())
        digit_chars = sum(1 for c in content if c.isdigit())
        total = max(alpha_chars + digit_chars, 1)
        density = digit_chars / total
        if density >= _STRUCTURAL_THRESHOLDS["numeric_density"] and total > 200:
            alerts.append({
                "level": "warning",
                "rule": "privacy_numeric_density",
                "message": f"High numeric density in {file_path}: {density:.0%}",
            })

        # JSON/CSV 嵌入 markdown
        json_blocks = content.count("```json") + content.count('"summary"') + content.count('"results"')
        csv_blocks = content.count("```csv")
        if json_blocks >= 1 or csv_blocks >= 1:
            alerts.append({
                "level": "warning",
                "rule": "privacy_embedded_data",
                "message": f"Embedded data block in {file_path}: json={json_blocks} csv={csv_blocks}",
            })

    return alerts


def scan_files_privacy(
    workspace_path: str,
    file_list: list[str],
    level: int = 2,
    deep_scan: bool = False,
) -> list[dict]:
    """扫描变更文件列表的隐私风险。返回所有告警。"""
    from pathlib import Path
    ws = Path(workspace_path)
    all_alerts = []

    # 只检查文本文件
    for rel_path in file_list:
        fpath = ws / rel_path
        if not fpath.exists():
            continue
        # 跳过二进制
        try:
            content = fpath.read_text(encoding="utf-8", errors="ignore")
        except (OSError, UnicodeDecodeError):
            continue
        # 跳过超大文件（>1MB）
        if len(content) > 1024 * 1024:
            continue
        alerts = scan_privacy(rel_path, content, level=level, deep_scan=deep_scan)
        all_alerts.extend(alerts)

    return all_alerts
