"""测试 Authorship 过滤 — commit message + 代码注释 + AI 配置文件排除"""

from backend.core.authorship import (
    strip_commit_message,
    strip_code_comments,
    get_ai_exclude_patterns,
    is_ai_config_file,
    strip_authorship_from_message,
    strip_authorship_from_code,
)


# ── commit message 清洗 ─────────────────────────────────

def test_strip_coauthored_by():
    msg = "feat: add login\n\nCo-authored-by: Claude\nSigned-off-by: ChatGPT"
    result = strip_commit_message(msg)
    assert "Co-authored-by" not in result
    assert "Signed-off-by" not in result
    assert "feat: add login" in result


def test_strip_generated_by():
    msg = "fix: bug\n\nGenerated with Claude\nvia Copilot"
    result = strip_commit_message(msg)
    assert "Generated with" not in result
    assert "via Copilot" not in result


def test_strip_generated_with_bracketed():
    msg = "docs: update\n\n(Generated with Cursor)"
    result = strip_commit_message(msg)
    assert "Generated" not in result


def test_clean_message_unchanged():
    msg = "feat: add feature\n\nImplemented login endpoint\n\nFixes #42"
    result = strip_commit_message(msg)
    assert result == msg


def test_strip_multiple_ai_refs():
    msg = "feat: x\n\nCo-authored-by: Claude\nCo-authored-by: ChatGPT\nvia Gemini"
    result = strip_commit_message(msg)
    assert "Co-authored-by" not in result
    assert "via Gemini" not in result


def test_strip_empty_message():
    assert strip_commit_message("") == ""


# ── 代码注释清洗（激进模式） ───────────────────────────

def test_strip_ai_comments():
    code = "# Generated by Claude\nimport os\n# via ChatGPT: fix this\ndef main(): pass"
    result = strip_code_comments(code)
    assert "# Generated by" not in result
    assert "# via ChatGPT" not in result
    assert "import os" in result
    assert "def main(): pass" in result


def test_strip_ai_block_comment():
    code = "/* Generated by Claude */\nint x = 1;"
    result = strip_code_comments(code)
    assert "/* Generated" not in result
    assert "int x = 1;" in result


def test_strip_ai_slash_comment():
    code = "// Generated with Copilot\nconst x = 1;\n// auto-generated by GPT\nconst y = 2;"
    result = strip_code_comments(code)
    assert "Generated" not in result
    assert "auto-generated" not in result
    assert "const x = 1" in result
    assert "const y = 2" in result


def test_keep_normal_comments():
    code = "# This is a normal comment\nimport os\n# TODO: refactor"
    result = strip_code_comments(code)
    assert "# This is a normal comment" in result
    assert "# TODO: refactor" in result


def test_strip_code_empty():
    assert strip_code_comments("") == ""


# ── AI 配置文件排除 ────────────────────────────────────

def test_is_ai_config_claude_md():
    assert is_ai_config_file("CLAUDE.md") is True


def test_is_ai_config_claude_dir():
    assert is_ai_config_file(".claude/memory.json") is True


def test_is_ai_config_codex():
    assert is_ai_config_file(".codex/project.json") is True


def test_is_ai_config_cursor():
    assert is_ai_config_file(".cursor/rules") is True


def test_is_not_ai_config():
    assert is_ai_config_file("src/main.py") is False
    assert is_ai_config_file("README.md") is False
    assert is_ai_config_file(".git/config") is False


def test_custom_exclude_patterns():
    custom = ["CLAUDE.md", "docs/ai/"]
    assert is_ai_config_file("docs/ai/design.md", custom) is True
    assert is_ai_config_file(".claude/memory.json", custom) is False


# ── 便利函数 ──────────────────────────────────────────

def test_strip_authorship_from_message():
    assert strip_authorship_from_message("Co-authored-by: Claude") != "Co-authored-by: Claude"


def test_strip_authorship_from_code_standard():
    code = "# Generated by Claude\nx = 1"
    assert strip_authorship_from_code(code, aggressive=False) == code


def test_strip_authorship_from_code_aggressive():
    code = "# Generated by Claude\nx = 1"
    result = strip_authorship_from_code(code, aggressive=True)
    assert "Generated" not in result


# ── 默认模式 ──────────────────────────────────────────

def test_get_default_patterns():
    patterns = get_ai_exclude_patterns()
    assert "CLAUDE.md" in patterns
    assert ".claude/" in patterns
    assert ".codex/" in patterns
    assert ".cursor/" in patterns
