"""CLI verb implementations — headless, no Qt/Rich dependency."""
from .commands import (
    _cmd_list,
    _cmd_status,
    _cmd_sync,
    _cmd_daemon,
    _cmd_trial,
    _cmd_formalize,
    _cmd_scan,
    _cmd_push,
    _cmd_session,
    _cmd_history,
    _cmd_release,
    _cmd_suggest,
    _init_session,
)
from .commands_ext import (
    _cmd_governance,
    _cmd_export,
    _cmd_template,
    _cmd_formal,
    _cmd_memory,
    _cmd_contract,
    _cmd_lesson,
)

__all__ = [
    "_cmd_list",
    "_cmd_status",
    "_cmd_sync",
    "_cmd_daemon",
    "_cmd_trial",
    "_cmd_formalize",
    "_cmd_scan",
    "_cmd_push",
    "_cmd_session",
    "_cmd_history",
    "_cmd_release",
    "_cmd_suggest",
    "_cmd_governance",
    "_cmd_export",
    "_cmd_template",
    "_cmd_formal",
    "_cmd_memory",
    "_cmd_contract",
    "_cmd_lesson",
    "_init_session",
]
